### PR TITLE
Protected RenderDiscordSettings from missing data

### PR DESCRIPTION
**Pull request by Argembarger**

### CODE REVIEW

**Review by FabianvZ — APPROVED** [review]
I think that the only way to trigger missing data is to edit the save file for the settings manually. But it couldn't hurt to add this check.

Thank you for your contribution.

**Comment by Argembarger** [comment]
> I think that the only way to trigger missing data is to edit the save file for the settings manually. But it couldn't hurt to add this check.
> 
> Thank you for your contribution.

It was interesting -- after the most recent major campaign / openplanet update, the Discord tab blanked out for me and I did some digging. I was literally playing the game during the update rollout so. Who knows lol, but no (deliberate) manual file manipulation on my part

**Comment by Argembarger** [comment]
(My Eclipse Mixed Cup 7 team "Untitled EMC Team" is using this plugin btw lol)

**Comment by FabianvZ** [comment]
> > I think that the only way to trigger missing data is to edit the save file for the settings manually. But it couldn't hurt to add this check.
> > Thank you for your contribution.
> 
> It was interesting -- after the most recent major campaign / openplanet update, the Discord tab blanked out for me and I did some digging. I was literally playing the game during the update rollout so. Who knows lol, but no (deliberate) manual file manipulation on my part

That is interesting. I'll have a closer look to see what could possibly cause this

**Comment by FabianvZ** [comment]
> (My Eclipse Mixed Cup 7 team "Untitled EMC Team" is using this plugin btw lol)

That is nice to hear. Me and Lokulicious made this plugin for ourselves, but made it so that other people could also use it. It is very interesting to see the amount of downloads go way higher than we expected.

**Pull request merged**
